### ISSUE TITLE
Tweets often lost when sending

### ISSUE THREAD

**Issue by maxim** [freeatnet/pwitter#3]
This is the issue with latest version of original pwitter. Half the time tweets are lost when attempting to send. Not sure if you addressed it yet. (Pwitter is the only client that seems to get it right for me so I really appreciate your effort. Should learn ObjC+Cocoa myself.)

**Comment by freeatnet** [comment]
Hey Max,
sorry for the late reply. I believe, that was an issue with rate limiting, authentication, and related. As of 2.0, Pwitter uses OAuth, so no problems should appear. If you are still seeing tweets being lost, please, open a new ticket.
